# HTTP Server (Tomcat) Port
server: 
  host: 51.79.159.7
  port: 5555
  resource:
    location: file:C:/app_runs/unlimits-resources/resource
  database:
    host: 15.235.207.206
    port: 3306
    username: unlimits_usr
    password: JJeV!EhBbuR
    schema: unlimits_client
  gateway:
    host: 51.79.159.7
    port: 8080
    endpoint: client
  eureka:
    host: 51.79.159.7
    port: 1111
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: true

spring:
   application:
     name: unlimits_client
   main:
     allow-bean-definition-overriding: true
   sql.init.mode: always
   datasource:
     driverClassName: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://${server.database.host}:${server.database.port}/${server.database.schema}?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
     username: ${server.database.username}
     password: ${server.database.password}
     show-sql: true
   jpa: 
     hibernate: 
       dialect: org.hibernate.dialect.MySQLDialect
       ddl-auto: update
       format_sql: true
       show_sql: true
       naming: 
         physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /api/swagger-ui.html
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
openapi:
  service:
    title: client
    version: 1.0.0
    url: http://${server.gateway.host}:${server.gateway.port}/${server.gateway.endpoint} #api gateway url
    
# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://${server.gateway.host}:${server.gateway.port}/eureka/       