# HTTP Server (Tomcat) Port
server: 
  port: 5555
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: true

spring:
   application:
     name: unlimits_client
   main:
     allow-bean-definition-overriding: true
   sql.init.mode: always
   datasource:
     driverClassName: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/unlimits_client?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
     username: root
     password: root
     show-sql: true
   jpa: 
     hibernate: 
       dialect: org.hibernate.dialect.MySQLDialect
       ddl-auto: update
       format_sql: true
       show_sql: true
       naming: 
         physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /api/swagger-ui.html
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
openapi:
  service:
    title: client
    version: 1.0.0
    url: http://localhost:5555 #api gateway url
    
# Discovery Server Access
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:1111/eureka/       